config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"

  resources :chapters, only: [:index, :show]
  match '/meetups/:slug' => 'meetups#show', via: :get

  get 'about', to: 'home#about'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    allroles = []
    user.roles.each do |r|
      allroles << r.name
    end
    if allroles.include? "webmistress"
      can :manage, :all
    elsif allroles.include? "admin"
      can :manage, user.chapter
      can :manage, user.bio
      can :manage, Sponsor
      can :read, :all
    else
      can :view, :all
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :bio
  belongs_to :chapter
  accepts_nested_attributes_for :roles
end

app/models/bio.rb
class Bio < ActiveRecord::Base
  resourcify
  belongs_to :admin_user
  belongs_to :chapter

  mount_uploader :image, ProfileImageUploader
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  extend FriendlyId
  friendly_id :chapter, use: [:slugged, :history]

  resourcify
  has_many :admin_users
  has_many :sponsors
  has_many :bios

  geocoded_by :geo
  after_validation :geocode
  after_validation :geocode, :if => :geo_changed?

  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geocoded = results.first
      obj.state = geocoded.state
    end
  end
  after_validation :reverse_geocode
end

app/models/role.rb
class Role < ActiveRecord::Base
  resourcify
  has_and_belongs_to_many :admin_users, :join_table => :admin_users_roles
  belongs_to :resource, :polymorphic => true

  scopify
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  resourcify
  belongs_to :chapter
  mount_uploader :image, SponsorImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def access_denied(exception)
    redirect_to admin_path, :alert => exception.message
  end


  # private
  #
  # def after_sign_out_path_for(resource_or_scope)
  #   # binding.pry
  #   root_path
  # end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  require 'rails_autolink'
  def index
    @chapters = Chapter.all
    states = {}
    @chapters.each do |l|
      if states[l.state]
        states[l.state] << l.chapter
      else
        states[l.state] = [l.chapter]
      end
    end
    @states = states.to_a.sort

  respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @chapters }
  end
end

  def show
    @chapter = Chapter.friendly.find(params[:id])
    if request.path != chapter_path(@chapter)
      redirect_to @chapter, status: :moved_permanently
    end
    @users = @chapter.admin_users
    @sponsors = @chapter.sponsors

    @bios = @chapter.bios
    @leaders = @bios.where(title: "LEADERS")
    @instructors = @bios.where(title: "INSTRUCTORS")

    api = MeetupApi.new
    @events = api.events(group_id: @chapter.meetup_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  @chapters = Chapter.all
  @chapter = Chapter.all
  end

  def about
  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController

  def show
    ## Someday there will be caching here!
    @chapter = Chapter.find_by(slug: params[:slug])

    params = { group_id: @chapter.meetup_id, key: ENV["MEETUP_API_KEY"]}
    meetup_api = MeetupApi.new
    @glob = meetup_api.events(params)
    @results = @glob["results"]

    respond_to do |format|
      format.json { render json: @results }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
  def image_route(s)
    "state_map/#{s.parameterize}.png"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/chapters/_meetup_map.html.erb
<p class="meetup-map hide">
  <%% if( typeof venue !== "undefined" && venue.lat !== 0) { %>
    <img src= "http://maps.google.com/maps/api/staticmap?size=800x450&sensor=false&zoom=16&markers=<%%= venue.lat %>%2C<%%= venue.lon %>" alt="chapter map">
  <%% } %>
</p>

app/views/chapters/index.html.erb
  <section class="main-container">
  <div class="container">

    <div class="underlined-headline">
      <h2>We are now in <%= @chapters.count %> cities!</h2>
        <hr><p class="subtitle hide">Don't see your hometown?
          <% if current_admin_user != nil %>
            <%= link_to "Start a new chapter!", "#{root_path}admin/chapters/new" %></p>
            <% else %>
            <a href="https://docs.google.com/a/girldevelopit.com/forms/d/1IwGncJ6_69MWa2_rrikO5Q3DLriA04Eq9x0BUnxkwTw/viewform?edit_requested=true#start=invite">Start a new chapter!</a></p>
          <% end %>
        </p>
    </div>

    <section class="state-index hide">
      <% @states.each do |s| %>
        <div class="state-container">
          <div class="state"><%= image_tag(image_route(s[0])) %></div>
          <hr>
          <h2><%= s[0] %></h2>
          <% s[1].each do |l| %>
            <h3 class="large"><%= link_to l, chapter_path(l.parameterize) %></h3>
          <% end %>
        </div>
    <% end %>
    </section>

    <section id="state-list">
      <div class="accordion show">
        <% @states.each do |s| %>
          <section class="hidden">
            <h2><%= s[0] %></h2>
            <ul>
              <% s[1].each do |l| %>
                <li><h3><%= link_to l, chapter_path(l.parameterize) %><h3></li>
              <% end %>
            </ul>
          </section>
        <% end %>
      </div>
    </section>
  </div>
  </section>

app/views/chapters/show.html.erb
<section class="main-container">
  <div class="container">
    <aside class="chapter-aside">
      <div class="state-container-aside">
        <%= link_to image_tag(image_route(@chapter.state)), chapters_path %>
      </div>
      <hr>
      <h1><%= @chapter.chapter %></h1>

      <%= render partial: "social_media_chapter", locals: {user: @chapter} %>

      <p class="subtitle">- don't be shy -</p>
      <%= link_to "{ Join Us }", "http://www.meetup.com/#{@chapter.meetup}", :class=>"button" %>

      <!-- <% if @chapter.sponsors.count != 0 %>
        <div class="hide">
          <div class="sponsors">
            <h2>Sponsors</h2>
            <div id="logos">
              <% @sponsors.each do |sponsor| %>
                <% if sponsor.image? %>
                  <p><%#= link_to image_tag(sponsor.image.url), sponsor.url %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %> -->
    </aside>

    <section id="content-section">
      <div id="headline">
        <%= image_tag 'pencil.png' %>
        <h2>Upcoming Events</h2>
      </div>

      <div class="classes">
      </div>

      <% if @leaders.count != 0 %>
        <div id="headline">
          <%= image_tag 'flourish.png' %>
          <h2>Chapter Leaders</h2>
        </div>
      <% end %>

      <div class="profiles">

        <% @leaders.each do |bio| %>
          <div class="single-profile">
            <div class="profile-img">
              <% if bio.image? %>
                <%= image_tag bio.image %>
              <% elsif bio.pic_link? %>
                <%= image_tag bio.pic_link %>
              <% else %>
                <%= image_tag "photo-not-available.jpg" %>
              <% end %>
            </div>

            <div class="profile-content">
              <h3><%= bio.name %></h3>
              <% if bio.info[0, 3] == "<p>" %>
                <%= bio.info.html_safe %>
              <% else %>
                <%= auto_link(simple_format(bio.info.html_safe)) %>
              <% end %>
              <%= render partial: "social_media_bio", locals: {bio: bio} %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="profiles">
        <% if @instructors.count != 0 %>
          <div id="headline">
            <%= image_tag 'apple.png' %>
            <h2>The Instructors</h2>
          </div>
        <% end %>

        <% @instructors.each do |bio| %>
          <div class="single-profile">
            <div class="profile-img">
              <% if bio.image? %>
                <%= image_tag bio.image %>
              <% elsif bio.pic_link? %>
                <%= image_tag bio.pic_link %>
              <% else %>
                <%= image_tag "photo-not-available.jpg" %>
              <% end %>
            </div>

            <div class="profile-content">
              <h3><%= bio.name %></h3>
              <% if bio.info[0, 3] == "<p>" %>
                <%= bio.info.html_safe %>
              <% else %>
                <%= simple_format(bio.info.html_safe) %>
              <% end %>
              <%= render partial: "social_media_bio", locals: {bio: bio} %>

            </div>
          </div>
        <% end %>
      </div>

      <script type="text/template" id="meetup">

        <h3><a href=" <%%= event_url %>"><%%= name %></a></h3>
        <p class="subtitle">[ <%%=moment(time).format("dddd, MMMM Do YYYY, h:mm a")%>
          <%% if(typeof venue !== "undefined") { %>
            , <a href=" http://maps.google.com/?q=<%%= venue.address_1 %>, <%%= venue.city %>, <%%= venue.state %>"><%%= venue.address_1 %>,<%%= venue.city %>,<%%= venue.state %></a>
          <%% } %>
         ] </p>
        <p><%%= description.substring(0, 400) %><a href="<%%= event_url %>">...read more</a></p>
        <a href="<%%= event_url %>" class="button">RSVP</a>
        <%= render partial: "meetup_map"%>
      </script>


      <script type="text/javascript">
        var meetup_url = '/meetups/<%= params[:id] %>.json';
        $.getJSON(meetup_url).done(function (classesData){
            console.log("here are all the classes", classesData);
          if(classesData.length>0) {
            var classesArr = classesData.slice(0,3);
            console.log(classesArr);
            var oneClass = '';
            var classes = $('#meetup').html();
              _.each(classesArr, function (one) {
              oneClass += _.template(classes, one);
                $(".classes").html(oneClass);
            });
          } else {
            $(".classes").html("<p class=\"uhOh\">Sadly, no meetups are currently scheduled for this Chapter. <a href=\"http://meetup. com/<%= @chapter.meetup %>\">Join our meetup group</a> to be notified when a new meetup is happening. Thanks for visiting us!</p>")};
          });

      </script>
    </section>
  </div>
</section>

app/views/home/about.html.erb
<section class="main-container">

  <div class="container">

    <section class="mission">
      <div class="underlined-headline">
        <h2>Our Mission</h2>
        <hr>
      </div>
      <p class="large">Girl Develop It is a nonprofit organization that exists to provide affordable and accessible programs for women interested in learning web and software development. Through mentorship and hands-on instruction Girl Develop It can help them reach their goals.</p>
    </section>

    <div class="vision">
    <h3 class="subtitle">[ Our Vision ]</h3>
    <p>Our vision is to create a network of empowered women who feel confident in their abilities to code and build beautiful web and mobile applications. By teaching women around the world from diverse backgrounds to learn software development, we can help women improve their careers and confidence in their everyday lives.</p>
    </div>

    <div class="values">
    <h3 class="subtitle">[ Our Values ]</h3>
    <p>We are committed to making sure women of all ages, races, education levels, income, and upbringing can build confidence in their skill set to develop web and mobile applications. Our goal is to provide powerful hands-on programs to women seeking professional help in software development and create basic to advanced web and mobile applications.</p>
    </div>

  </div>

  <section class="support">
    <div class="container">
      <div class="underlined-headline">
        <h2>Your Amazing Support</h2>
        <hr>
      </div>
      <p class="large">Thank you for supporting Girl Develop It on our mission to make software development easy, affordable and accessible to all women. Your contribution helps us expand our mission to create great programs and opportunities for women learning to code. We are in the final stages of completing our 501(c)(3) status through the Internal Revenue Service.</p>
    </div>
  </section>


  <div class="container">
    <div id="headline">
      <%= image_tag 'flourish.png' %>
      <h2>Our Founders</h2>
    </div>

      <div class="profile-left">
          <%= image_tag 'board/sara.jpg' %>
          <h3>Sara Chipps // Co-founder</h3>
          <p>Sara is the CTO of <a href="http://www.levo.com/">Levo League,</a> where she focuses on developer happiness as a metric for success. In 2010, she cofounded Girl Develop It because she thinks that the development community could use a few more ladies.</p>
          <p>Sara blogs at <a href="http://sarajchipps.com/">SaraJChipps.com</a> and enjoys speaking to and meeting with diverse groups from the Girl Scouts to straight up code junkies. Sara's favorite language is JavaScript, and she thinks coffee is for drinking not coding.</p>
      </div>


      <div class="profile-right">
          <%= image_tag 'board/vanessahurst.jpg' %>
          <h3>Vanessa Hurst // Co-founder</h3>
          <p><a href="http://vanessahurst.com/">Vanessa</a> believes every person should be empowered to use technology to make the world a better place. She started Girl Develop It to provide judgment-free learning opportunities with a focus on results, and to support women teaching and learning from one another. She’s a lifetime Girl Scout, a teacher, and a passionate supporter of open source software.</p>
          <p>Vanessa is currently building <a href="https://www.codemontage.com/">CodeMontage</a> to help people improve their software skills while improving the world. She also founded and organizes <a href="http://www.developersforgood.org/">Developers for Good</a> to connect technologists who want to use their skills to make an impact with organizations that need help. Previously, Vanessa led the database and analytics efforts at <a href="https://www.paperlesspost.com/">Paperless Post.</a></p>
      </div>

      <div id="headline">
        <%= image_tag 'flourish.png' %>
        <h2>The Board</h2>
      </div>

      <div class="profile-left">
          <%= image_tag 'board/corinnewarnshuis.jpg' %>
          <h3>Corinne Warnshuis</h3>
          <p>Corinne is the Executive Director of Girl Develop It. After graduating from University of California, Santa Cruz with a degree in Sociology and Film & Digital Media, she moved to Philadelphia. Prior to becoming the first ED of Girl Develop It, she was the co-leader of the Philly chapter for two years. She also previously worked for the Technical.ly news network, an online publication that covers technology issues and organizes regular events in Philly, Baltimore and Brooklyn. She has also worked in community relations at WHYY.org and written freelance for various online publications. Corinne sits on the Board of Directors for the Prometheus Radio Project. In her spare time, she is a regular contributor to Rad Girls, co-curates Ignite Philly and loves learning hands-on skills, playing with her cats and watching documentaries.</p>
      </div>


      <div class="profile-right">
          <%= image_tag 'board/marc.png' %>
          <h3>Marc Hedlund</h3>
          <p>Marc Hedlund is VP Engineering at Stripe, the online payments company that allows businesses to start accepting payments from all over the world in minutes, with just a few lines of code. At Stripe, Marc is responsible for growing and managing Stripe's engineering team.</p>
          <p>Prior to Stripe, Marc was SVP of Product Development and Engineering at Etsy in New York. One of Stripe's 17 former founders, he also co-founded and was CEO of Wesabe, an online personal finance company. Perviously, Marc held leadership roles at O'Reilly Media, Lucasfilm, and Organic Online. Early in his career, Marc authored one of the first shopping carts on the web.</p>
          <p>Marc serves on the board of directors for Code:2040, a non-profit working to bring more Black and Latina/o engineers into tech startups. Marc is a graduate of Reed College.</p>
      </div>


      <div class="profile-left">
          <%= image_tag 'board/alanna.jpg' %>
          <h3>Alanna Gombert</h3>
          <p>Alanna Gombert is General Manager of CatalystDesk, Conde Nast's digital media trading platform.</p>
          <p>Alanna joined Condé Nast from Google by way of Admeld where she ran the trading desk, agency and demand-side platform relationships and helped grow RTB from an idea to a killer business.</p>
          <p>Prior to Admeld, Alanna worked at Right Media, the first online advertising exchange, where she focused on ad selection algorithms and market dynamics. Right Media was acquired by Yahoo in 2007. Her early career included stints with Nielsen, DoubleClick and the finance world with JP Morgan Chase and Commerzbank. Advertising has allowed her to travel the world and she has experience in international markets including EMEA, APAC, and Latin America.</p>
          <p>Alanna is also very active in the startup community in NYC. She enjoys advising startups, angel investing, and is a proud board member of Rare Crowds and Snowball Technologies.</p>
          <p>She lives in Brooklyn with Husband Gombert and Baby Gombert, likes Thai food, and is trying desperately to learn how to meditate.</p>
      </div>

      <div class="profile-right">
          <%= image_tag 'board/erynn.jpg' %>
          <h3>Erynn Peterson</h3>
          <p>Erynn Petersen is Executive Director of Outercurve, an OSS foundation focused on developing open source projects between enterprise software companies. She is also a founder at Station082, which is dedicated to providing technology access to rural kids.</p>
          <p>Erynn joined Outercurve after spending a year at Activate Consulting where she advised media companies in redefining corporate and product strategies around technology investments.</p>
          <p>Prior to Activate, Erynn was SVP of Paid Services Engineering at AOL, where her teams built the tools, frameworks, and services that helped AOL subscribers safely and securely access content and applications online.Her early career included Amazon.com, where she worked on projects including the launch of the third party sellers platform, several startups, and Microsoft, where she was on the launch team for Bing paid advertising. She combines product management and technical management skills, and spends time teaching for Girl Develop It. She has spoken at events ranging from OSCON to SXSW and is a strong proponent of getting more people into technology and engineering roles.</p>
          <p>She lives in bucolic Enumclaw, Washington with her family and her mongrel terrier, Lebowski, and invites anyone driving through to stop by for coffee.</p>
      </div>

      <div class="profile-left">
          <%= image_tag 'board/carajo.jpg' %>
          <h3>Cara Jo Miller</h3>
          <p>Cara Jo is the Lead UI/UX Designer at Simple Energy, a Boulder company whose mission is to help people save energy.</p>
          <p>Before Simple Energy Cara Jo was the Lead Designer at Are You a Human and the Detroit Media Partnership, both based out of downtown Detroit. While in Detroit Cara Jo was very involved in the technical community and led several groups focused on getting more people involved in technology. In addition to those organizations Cara Jo helped co-lead the Detroit chapter of GDI before moving to Boulder to start a local chapter in the mountains.</p>
          <p>In addition to being Co-leader for the Boulder chapter Cara Jo also serves as the Chapter Leader Board member, making sure that each Chapter Leader get’s the resources they need to bring the GDI mission to their local communities.</p>
          <p>Cara Jo lives in beautiful Boulder, Colorado where she trains for marathons, bikes, and enjoys backpacking in the mountains.</p>
      </div>


    </div>

    <section class="code">
      <div class="container">
        <div class="underlined-headline">
          <h2>Code of Conduct</h2>
          <hr>
        </div>
        <p>Girl Develop It is dedicated to providing a harassment-free community and learning experience for everyone, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, or religion. We expect all attendees to show respect and courtesy to other attendees throughout Girl Develop It classes and events. Sexual language and imagery is not appropriate for any Girl Develop It event. Girl Develop It participants violating these rules may be sanctioned or expelled from our events or online discussion boards without a refund at the discretion of the event organizers.</P>
        <p>Harassment includes offensive verbal comments related to gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, or religion; sexual images in public spaces; deliberate intimidation; stalking; following; harassing photography or recording; sustained disruption of talks or other events; inappropriate physical contact; and unwelcome sexual attention. Adults who identify as men are welcome at our events, and it is expected that all participants be treated with equal respect. We do not tolerate harassment of Girl Develop It participants in any form. All communication should be appropriate for a professional audience. Participants asked to stop any harassing behavior are expected to comply immediately.</p>
        <p>Your privacy is important to us. While photographs may be taken in class and can be shared by group members in the group’s meetup page, no photograph shall be used for promotional purposes without verbal and/or written consent of the attendees. If a group photograph is taken, your participation will serve as your agreement to the use of such a photograph for Girl Develop It promotional purposes. If you are uncomfortable having your photograph shared, please let us know. Teachers, event organizers, volunteers, and hosts are also subject to the anti-harassment policy. In particular, teachers/hosts/organizers should not use sexualized images, activities, or other material. GDI organizers, teachers, teachers assistants, and event hosts (including volunteers) should not use sexualized clothing/uniforms/costumes, or otherwise create a sexualized environment.</p>
        <p>If a participant engages in harassing behavior, the Girl Develop It organizers may take any action they deem appropriate, including warning the offender or expelling him or her from the class/event/meetup group [with no refund]. If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact your local Chapter Leader(s) immediately. Contact information for your local Chapter Leader can be found on <%= link_to "#{root_url.chop!}#{chapters_path}", chapters_path %>.</p>
        <p>Girl Develop It Chapter Leaders/Teachers/Event Organizers will be happy to help members contact local law enforcement, provide escorts when possible and with reasonable notice, or otherwise assist those experiencing harassment to feel safe for the duration of the event/class. We value your attendance.</p>
        <p>Girl Develop It expects participants to follow these rules at all Girl Develop It social events and in online discourse.</p>
        <p>If you have any questions, please contact your local chapter. Contact information for your local Chapter Leader can be found at <%= link_to "#{root_url.chop!}#{chapters_path}", chapters_path %>.</p>
      </div>
    </section>





  </div>
</section>

app/views/home/index.html.erb
  <div class="opener">
    <%#= image_tag("photo2.png") %>
    <h1><span class="animated fadeInLeftBig">Don't be shy</span> <%= image_tag("flourish-med.png" , class: "hide") %> <span class="animated fadeInRightBig">Develop it</span></h1>
  </div>

  <div class="container" >
  	<section class="mission-statement">
      <div class="underlined-headline">
        <h2>Who are we?</h2>
        <hr>
      </div>
    	<p class="large">Girl Develop It is a nonprofit organization that exists to provide affordable and accessible programs for women interested in learning web and software development. Through mentorship and hands-on instruction Girl Develop It helps woman of diverse backgrounds reach their goals. Our vision is to create a network of empowered women who are confident in their abilities to code and build beautiful web applications. Through teaching women around the world to learn software development, we can help them improve their careers and the confidence they carry with them in their everyday lives.</p>
      <%= link_to "[ Learn more ]", about_path, :class=>"subtitle"%>
    </section>
  </div>

  <section class="map">
    <div class="container">
    	<div class="underlined-headline">
        <h2>We are now in <%= @chapters.count %> cities!</h2>
        <hr><p class="subtitle hide">Don't see your hometown?
          <% if current_admin_user != nil %>
            <%= link_to "Start a new chapter!", "#{root_path}admin/chapters/new" %></p>
            <% else %>
            <a href="https://docs.google.com/a/girldevelopit.com/forms/d/1IwGncJ6_69MWa2_rrikO5Q3DLriA04Eq9x0BUnxkwTw/viewform?edit_requested=true#start=invite">Start a new chapter!</a></p>
          <% end %>
        </p>
        <%=link_to "Find GDI in your hometown!", chapters_path, :class=>" subtitle show-inline"%>
      </div>
        <div class="us_map hide">
          <div class="map"></div>
        </div>
    </div>
  </section>

  <section class="stats-section">
    <div class="container">
      <div class="stats">
        <%= image_tag("stat-25.png") %>
        <p>Women hold only 25% of the 3,816,000 computing related occupations in the US.</p>
      </div>
      <div class="stats">
        <%= image_tag("stat-58.png") %>
        <p>Woman obtain 58% of bachelor’s degrees in the U.S, but less than 18% of those degrees are in computer science. (Compared to 1984, when women earned 37%)</p>
      </div>
      <div class="stats">
        <%= image_tag("stat-34.png") %>
        <p>Tech companies with more women in management have a 34% higher return of investment. Diverse tech and startup teams are critical for innovation.</p>
      </div>
    </div>
  </section>

  <div class="press-logos">
    <h3>{ As seen in }</h3>
    <%#= image_tag("press-logos.png") %>
    <%= link_to image_tag("as_seen_in/code_org.png"), "https://www.youtube.com/watch?v=nKIu9yen5nc" %>
    <%= link_to image_tag("as_seen_in/tnyt.png"), "http://www.nytimes.com/2012/03/28/technology/for-an-edge-on-the-internet-computer-code-gains-a-following.html" %>
    <%= link_to image_tag("as_seen_in/ted.png"), "http://blog.ted.com/2013/01/29/10-places-where-anyone-can-learn-to-code/" %>
    <%= link_to image_tag("as_seen_in/fast_company.png"), "http://www.fastcompany.com/1776382/female-geeks-flex-their-skills-ladies-only-hackathon" %>
    <%= link_to image_tag("as_seen_in/lifehacker.png"), "http://lifehacker.com/5872682/learn-to-code-in-2012-with-free-weekly-programming-lessons-from-codecademy" %>
  </div>
  <script>
    var chapter_id = "chapters/3";
  </script>

app/views/shared/_footer.html.erb
<footer>
	<div class="container">
		<div class="footer">
			<p class="subtitle hide">Don't see your city? Help bring Girl Develop It to your home town.</p>
			<p class="subtitle">To become a sponsor or for partnership opportunities, email  us at <%= mail_to "sponsorships@girldevelopit.com" %> </p>
			<nav class="navigation">
				<%= link_to "about", about_path %>
				<%#= link_to "partners", root_path, class: "hide" %>
				<a href="http://girldevelopit.tumblr.com/">blog</a>
				<% if current_admin_user != nil %>
					<%= link_to "Admin", admin_root_path %>
					<%= link_to "Logout", destroy_admin_user_session_path %>
				<% end %>
			</nav>
			<nav class="navigation">
				<a href="https://twitter.com/girldevelopit"><i class="fa fa-twitter"></i></a>
			  <a href="https://www.facebook.com/girldevelopit"><i class="fa fa-facebook"></i></a>
			</nav>
		</div>
	</div>
</footer>

app/views/shared/_header.html.erb
  <header>

    <div class="container">
      <%= link_to image_tag("gdi-logo.png"), root_path, class:"logo" %>
      <nav class="navigation">
        <ul>
          <li><%= link_to "home", root_path %></li>
          <li><%= link_to "about", about_path %></li>
          <li><%= link_to "chapters", chapters_path %></li>
          <li><%#= link_to "donate", donate_path %></li>
          <li><%#=link_to "resources", resources_path %></li>
        </ul>
        <ul>
          <li><a href="https://twitter.com/girldevelopit"><i class="fa fa-twitter"></i></a></li>
          <li><a href="https://www.facebook.com/girldevelopit"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </nav>

    <div>
  </header>